# Generated by Django 5.1.3 on 2025-02-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclovahz', '0002_song_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='songs',
            field=models.ManyToManyField(related_name='users', to='musiclovahz.song'),
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
