# Generated by Django 5.1.3 on 2025-03-04 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclovahz', '0003_user_songs_delete_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matches',
            field=models.ManyToManyField(related_name='matched_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
