# Generated by Django 5.1.3 on 2025-03-16 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclovahz', '0007_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unlikes',
            field=models.ManyToManyField(blank=True, related_name='unliked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
