# Generated by Django 5.1.3 on 2025-03-27 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musiclovahz', '0009_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
    ]
